# Generated by Django 3.0.8 on 2020-07-15 07:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT (0 0)', srid=4326),
        ),
    ]
