# Generated by Django 3.1.2 on 2020-10-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearbyshops', '0003_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormNear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearbyshops.buyer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nearbyshops.shop')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
