# Generated by Django 3.1.2 on 2020-10-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0002_remove_person_gender1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.earning')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.position')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='earning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.earning'),
        ),
        migrations.AddField(
            model_name='person',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.income'),
        ),
    ]
