# Generated by Django 3.1.2 on 2020-10-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0003_auto_20201020_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='earning',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
