# Generated by Django 3.1.2 on 2020-10-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0006_auto_20201020_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='earning',
        ),
        migrations.RemoveField(
            model_name='person',
            name='earning',
        ),
        migrations.AddField(
            model_name='income',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deed.position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='earning',
            field=models.CharField(default='NO', max_length=3),
        ),
        migrations.DeleteModel(
            name='Earning',
        ),
    ]
