# Generated by Django 3.1.2 on 2020-10-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0007_auto_20201020_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
