# Generated by Django 3.1.2 on 2020-10-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0008_auto_20201021_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='married',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
