# Generated by Django 3.1.2 on 2020-10-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0009_auto_20201022_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
