# Generated by Django 3.1.2 on 2020-10-24 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0011_auto_20201022_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deed.gender')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('married', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
                ('occupation', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('seller', models.BooleanField(default=True)),
                ('unique_id', models.CharField(max_length=50)),
                ('fwm_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.fmw')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.gender')),
            ],
        ),
    ]
