# Generated by Django 3.1.2 on 2020-10-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0012_fmw_salesdeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdeed',
            name='fwm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.fmw'),
        ),
        migrations.AlterField(
            model_name='salesdeed',
            name='fwm_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesdeed',
            name='occupation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='salesdeed',
            name='unique_id',
            field=models.CharField(max_length=150),
        ),
    ]
