# Generated by Django 3.1.2 on 2020-10-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0015_auto_20201025_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdeedrepresentative',
            name='unique_id',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesdeedrepresentative',
            name='representative_unique_id',
            field=models.CharField(max_length=150),
        ),
    ]
