# Generated by Django 3.1.2 on 2020-10-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0016_auto_20201025_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdeed',
            name='representy',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Guardian', 'Guardian')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
