# Generated by Django 3.1.2 on 2020-10-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0018_auto_20201025_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftDonorDeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(max_length=200)),
                ('representative_married', models.BooleanField(default=False)),
                ('representative_fwm_name', models.CharField(max_length=150)),
                ('representative_birth_date', models.DateField()),
                ('representative_occupation', models.CharField(max_length=150)),
                ('representative_address', models.TextField()),
                ('representative_unique_id', models.CharField(max_length=150, unique=True)),
                ('representative_fwm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.fmw')),
                ('representative_gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.gender')),
            ],
        ),
        migrations.CreateModel(
            name='GiftDeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('married', models.BooleanField(default=False)),
                ('fwm_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('occupation', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('unique_id', models.CharField(max_length=150, unique=True)),
                ('fwm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.fmw')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deed.gender')),
            ],
        ),
    ]
