# Generated by Django 3.1.2 on 2020-10-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deed', '0019_giftdeed_giftdonordeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=200)),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_address', models.TextField()),
                ('unique_id', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
